# Define a reusable logging block for Loki
x-logging-loki: &loki-logging
  driver: loki
  options:
    loki-url: ${LOKI_URL:-http://localhost:3100/loki/api/v1/push}
    labels: "service={{.Name}}"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - localchat
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/ping"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    logging: *loki-logging

  open-webui:
    image: ghcr.io/open-webui/open-webui
    container_name: open-webui
    ports:
      - "3000:8080"
    volumes:
      - ollama:/root/.ollama
      - open-webui:/app/backend/data
    env_file:
      - "./env/openwebui.env"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - localchat
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
    logging: *loki-logging

  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
      - "8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
      - searxng-cache:/var/cache/searxng
    env_file:
      - "./env/searxng.env"
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - localchat
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    logging: *loki-logging

  caddy:
    image: docker.io/library/caddy:2-alpine
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - "./env/caddy.env"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    restart: unless-stopped
    networks:
      - localchat
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    logging: *loki-logging

  apache-tika:
    image: apache/tika:latest-full
    container_name: apache-tika
    ports:
      - "9998:9998"
    restart: unless-stopped
    networks:
      - localchat
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9998/tika || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging: *loki-logging

  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    container_name: pipelines
    ports:
      - "9099:9099"
    volumes:
      - pipelines:/app/pipelines
    restart: unless-stopped
    networks:
      - localchat
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9099/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging: *loki-logging

  redis:
    image: docker.io/valkey/valkey:8-alpine
    container_name: redis
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - localchat
    volumes:
      - redis-data:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging: *loki-logging

  loki:
    image: grafana/loki:3.5.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config:/etc/loki
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped
    networks:
      - localchat
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.1
    container_name: cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    restart: unless-stopped
    networks:
      - localchat
    logging: *loki-logging

  grafana:
    image: grafana/grafana:11.6.3
    container_name: grafana
    ports:
      - "3001:3000"
    env_file:
      - "./env/grafana.env"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning:ro
    restart: unless-stopped
    networks:
      - localchat
    logging: *loki-logging

  prometheus:
    image: prom/prometheus:v3.3.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: unless-stopped
    networks:
      - localchat
    logging: *loki-logging

  playwright:
    image: mcr.microsoft.com/playwright:v1.49.1-noble
    container_name: playwright
    command: npx playwright@1.49.1 run-server --port 3000 --host 0.0.0.0
    restart: unless-stopped
    networks:
      - localchat
    logging: *loki-logging

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    env_file:
      - "./env/qdrant.env"
    volumes:
      - qdrant-data:/qdrant/storage
    restart: unless-stopped
    networks:
      - localchat
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    logging: *loki-logging

volumes:
  ollama:
    name: ollama
  open-webui:
    external: true
    name: open-webui
  pipelines:
    external: true
    name: pipelines
  redis-data:
    name: redis-data
  caddy-data:
    name: caddy-data
  searxng-cache:
    name: searxng-cache
  caddy-config:
    name: caddy-config
  grafana-data:
    name: grafana-data
  prometheus-data:
    name: prometheus-data
  qdrant-data:
    name: qdrant-data
  loki-data:
    name: loki-data

networks:
  localchat:
    name: localchat
    driver: bridge