services:
  open-webui:
    image: ghcr.io/open-webui/open-webui
    container_name: open-webui
    ports:
      - "3000:8080"
    volumes:
      - ollama:/root/.ollama
      - open-webui:/app/backend/data
    environment:
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL:-http://host.docker.internal:11434}
      ENABLE_RAG_WEB_SEARCH: True
      RAG_WEB_SEARCH_ENGINE: "searxng"
      # RAG_WEB_SEARCH_RESULT_COUNT: 3  # Optional, defaults likely fine
      # RAG_WEB_SEARCH_CONCURRENT_REQUESTS: 10 # Optional, defaults likely fine
      SEARXNG_QUERY_URL: "http://searxng:8080/search?q=<query>"
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: searxng
    ports:
      - "8080:8080" # Allow access from other containers on the network
    volumes:
      - ./searxng-instance/searxng:/etc/searxng:rw
    environment:
      - INSTANCE_NAME=searxng-instance
      - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS:-4}
      - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS:-4}
    env_file:
      - ./searxng-instance/searxng/.env
    restart: unless-stopped
    networks:
      - localchat
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  caddy:
    container_name: caddy
    image: docker.io/library/caddy:2-alpine
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data:rw
      - caddy-config:/config:rw
    environment:
      - SEARXNG_HOSTNAME=${SEARXNG_HOSTNAME:-http://localhost}
      - SEARXNG_TLS=${LETSENCRYPT_EMAIL:-internal}
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
  apache-tika:
    image: apache/tika:latest-full
    container_name: apache-tika
    ports:
      - "9998:9998"
    restart: always

  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    container_name: pipelines
    ports:
      - "9099:9099"
    volumes:
      - pipelines:/app/pipelines
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    networks:
      - localchat

  redis:
    container_name: redis
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - localchat
    volumes:
      - redis-data:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

volumes:
  ollama:
    name: ollama
    external: true
  open-webui:
    name: open-webui
    external: true
  searxng:
    name: searxng
  pipelines:
    name: pipelines
    external: true
  redis-data:
    name: redis-data
    external: false
  caddy-data:
    name: caddy-data
    external: false
  caddy-config:
    name: caddy-config
    external: false
  

networks:
  localchat:
    name: localchat
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: localchat