apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy # Use Grafana backend as proxy
    url: http://prometheus:9090 # URL of the Prometheus service
    isDefault: false # Set Loki or Prometheus as default as needed
    jsonData:
      timeInterval: "15s" # Match Prometheus scrape interval